### ISSUE TITLE
Get-PSWSUSUpdatePerClient throws ambiguity error

### ISSUE THREAD

**Issue by lansalot** [proxb/PoshWSUS#11]
Version 2.3. 

So I'm passing Computername, but being told I'm not.

```
PS C:\scripts\powershell> Get-PSWSUSUpdatePerClient -ComputerName SOMEPCNAME
Get-PSWSUSUpdatePerClient : Parameter cannot be processed because the parameter name 'Computer' is ambiguous. Possible matches include:
-Computername -ComputerTargetGroups.
At line:1 char:1
+ Get-PSWSUSUpdatePerClient -ComputerName ntweb1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PSWSUSUpdatePerClient], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameter,Get-PSWSUSUpdatePerClient
```

Also, ComputerTargetGroups isn't in Get-PSWSUSUpdatePerClient...?

**Comment by proxb** [comment]
This will be updated in the latest release to correct that error. ComputerTargetGroups is not listed as this is only to look at the updates per WSUS clients.

**Comment by lansalot** [comment]
Thanks - I see you've noted a few fixes, are you fixing-as-you-go, ie if I grab the latest right now will it be in it?

Superb cmdlets by the way - use them a lot.

**Comment by proxb** [comment]
Thanks! Currently I am hoping to push out an update this weekend with some of the changes. Assuming everything goes good then you should see a new update by Monday.

**Comment by proxb** [comment]
The latest update that I pushed out should fix this!

**Comment by lansalot** [comment]
Does indeed, thanks!
