### ISSUE TITLE
Bad help example for Connect-PSWSUSServer

### ISSUE THREAD

**Issue by Rarsic** [proxb/PoshWSUS#15]
First example in help for Connect-PSWSUSServer is this:

Connect-PSWSUSServer -PSWSUSserver "server1"

There is no parameter for -PSWSUSserver as the correct parameter is -WSUSserver as far as I can tell and there is no alias.

**Comment by proxb** [comment]
Looks like a bad find and replace in a previous update; thanks and it's been fixed!
