### ISSUE TITLE
Get-PSWSUSUpdateSummaryPerClient - Computer Name instead of Target ID?

### ISSUE THREAD

**Issue by p0wd3r** [proxb/PoshWSUS#22]
Using a very basic test, as recommended in the help portion of the code, this does not return the computer name...

**Get-PSWSUSUpdateSummaryPerClient -ComputerScope (New-PSWSUSComputerScope) -UpdateScope (New-PSWSUSUpdateScope)**

I can tell "New-PSWSUSComputerScope" to search for specific computer names or names containing stuff, but I cannot get the computername to be included in the output.  I tried using "Get-PSWSUSClient" to get the computer name (via the FullDomainName property) but the SummaryPerClient command won't accept the | cmdlet.  When I tried using the add-member option, the name is given as a single machine, or as system.object[] (and I'm sure I'm doing that part wrong!!).  I'm not a programmer, and rather fresh on the powershell stuff as well, but the .EXAMPLE for the SummaryPerClient command clearly shows a "Computer" field as part of the output, and I can't seem to get that script to show me that, only the targetID.  What am I missing?  And how can I translate the ComputerTargetID property into the Computer Name or FullDomainName property?

**Comment by lansalot** [comment]
This happened to me as well - I looked into it and found I was on 2.3.1.1. I updated to 2.3.1.5 and problem solved.

**Comment by p0wd3r** [comment]
Where did you find version 2.3.1.5?  I've been using 2.3.1.2, which is what is available here, and the issue persists.  Can you show me how you set up the command to get this data?

**Comment by lansalot** [comment]
I checked this again, to be sure (and also to ensure nothing else loaded was quirking matters...)

```
C:\pub>powershell -noprofile
Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS C:\pub> ipmo poshwsus
PS C:\pub> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-T...
Script     2.3.1.5    poshwsus                            {Add-PSWSUSClientT...
Script     1.0.0.13   PSReadline                          {Get-PSReadlineKey...


PS C:\pub> Connect-PSWSUSServer -WsusServer xxxxxx.etc

Name                 Version              PortNumber           ServerProtocolVe
                                                               rsion
----                 -------              ----------           ----------------
xxxx.etc...          6.2.9200.21848       80                   1.8


PS C:\pub> Get-PSWSUSUpdateSummaryPerClient -ComputerScope (New-PSWSUSComputerScope) -UpdateScope (New-PSWSUSUpdateScope)|select -first 1

Computer                  Installed Needed Failed PendingReboot
--------                  --------- ------ ------ -------------
server.xxx...             278       1      0      0


PS C:\pub>
```

**Comment by p0wd3r** [comment]
Strange, everything I have matches what you have exactly except for...
`
ModuleType Version    Name                                ExportedCommands                                                                 
---------- -------    ----                                ----------------                                                                 
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}                              
Manifest   3.1.0.0    Microsoft.Powershell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}               
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get-AuthenticodeSi...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                        
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-WSManCredSSP...}  
Script     0.0        PoshWSUS                            {Add-PSWSUSClientToGroup, Approve-PSWSUSUpdate, Connect-PSWSUSDatabaseServer, ...
`
Why does my PoshWSUS module show version 0.0?

**Comment by p0wd3r** [comment]
See above, combination of miss configuration and bug, this is now resolved, closing issue.
