### ISSUE TITLE
Server 2012 R2 WSUS: Computer Group Outputs Blank.

### ISSUE THREAD

**Issue by daricsmith** [proxb/PoshWSUS#8]
When running the command: Get-PoshWSUSUpdateSummaryPerGroup I get no output.

When running the command: Get-PoshWSUSUpdateSummaryPerClient the ComputerGroup column is empty.  Is there a library that needs to be added for this to fully work on Server 2012 WSUS?

**Comment by proxb** [comment]
I made some updates that might fix this. Can you download the latest bits and let me know the status?

**Comment by kennyboudreaux** [comment]
Unfortunately this still seems to be the case. I can run it from my Windows 10 workstation, but 2/3 windows server 2012 R2 machines don't work. 

The command runs but the computer values are all empty. 

![image](https://cloud.githubusercontent.com/assets/18561351/14655147/d1db1bf0-0635-11e6-8657-ae3fc31188aa.png)

**Comment by proxb** [comment]
Hmmm... Well I will give that another look and see what I can find. Appreciate the update!

**Comment by kennyboudreaux** [comment]
Much appreciated! Great tool anyway.

**Comment by jasonpearce** [comment]
I receive the same output as (kennyboudreaux commented 11 days ago). The column values for Computer are blank, but the remaining columns have data.

`PS C:\Windows\system32> Get-PSWSUSUpdateSummaryPerClient

Computer                  Installed Needed Failed PendingReboot
--------                  --------- ------ ------ -------------
                          296       1      6      0
                          338       1      0      0
                          295       1      0      0
                          186       0      0      0
                          3         3      1      0
                          238       1      0      0
                          333       1      0      0
                          236       1      0      0
                          238       1      0      0
                          247       81     13     0
                          229       9      0      0
                          274       26     0      0
                          136       8      82     0
                          320       1      0      0
                          237       1      3      0`

**Comment by proxb** [comment]
Thanks! I have this on my TODO list after I finish working on another item.

**Comment by rabidpitbull** [comment]
It looks like Powershell is not dealing well with references to $wsus in the PoshWSUS.Types.ps1xml file.

**Comment by ibenholt** [comment]
Hi! Any idea when this problem will be solved ? Would like to have an Update Summary report that shows the computer names....

**Comment by proxb** [comment]
Hoping within the month. This is slowly rising on my priority list so it will definitely be getting worked on.

**Comment by ibenholt** [comment]
Hi!

Any update on this issue ?

**Comment by ibenholt** [comment]
Hi! Any news here ? Waiting for you to fix this issue so I can automate the reporting from my WSUS... 

Best regards

**Comment by proxb** [comment]
I'm going to spend a little time this week to figure this out. I've been busy with another project so I haven't been able to really see what is going on with this command.

**Comment by proxb** [comment]
With the latest update, I tested on Windows 7 running PowerShell V5 (5.0.10586.117) and `Get-PSWSUSUpdateSummaryPerClient` worked as intended with the Computer property displaying information. I'm still looking at `Get-PSWSUSUpdateSummaryPerGroup` to see what is going on.

**Comment by proxb** [comment]
Latest update (2.3.1.5) should resolve this issue. Can you let me know the results of your testing?

**Comment by ibenholt** [comment]
Hi!

It works fine now, thank you!
